# Generated by Django 3.2.9 on 2021-11-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211121_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
