# Generated by Django 3.2.9 on 2021-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='todo.Category'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
