# Generated by Django 3.2.9 on 2021-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20211207_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
